#!/usr/bin/env bash

source "VERSION"

DIR=dg-quiz-${VERSION}

if [ -d "$DIR" ]; then
	rm -rf "$DIR"
fi

install -d "${DIR}"
install -d "${DIR}/config"

mvn clean || exit 1
mvn package || exit 1

install -m 0644 AUTHORS "$DIR"
install -m 0644 CHANGELOG.md "$DIR"
install -m 0644 README.md "$DIR"
install -m 0644 RUNNING.md "$DIR"
install -m 0644 src/main/resources/application-h2.properties "${DIR}/config"
install -m 0644 src/main/resources/application-mysql.properties "${DIR}/config"
install -m 0644 src/main/resources/application.properties "${DIR}/config"
install -m 0755 target/dg-quiz-${VERSION}.jar "$DIR"

zip -rv dg-quiz-${VERSION}.zip "$DIR"

echo "Done"
